export const surpriseMePrompts = [
  "A sleek, futuristic cityscape with neon-lit buildings nestled among the stars",
  "A robot explorer standing on an alien planet, surrounded by dazzling neon-colored flora",
  "A bustling intergalactic marketplace with robots and extraterrestrial beings trading under a canopy of sparkling stars",
  "A robot scientist conducting experiments in a high-tech laboratory, with holographic displays and neon accents",
  "A massive starship traveling through a vibrant nebula, with glowing neon engines propelling it forward",
  "A futuristic civilization on a distant planet, with towering neon-lit structures and advanced robotic infrastructure",
  "A robot musician performing on a neon stage, captivating an audience of both humans and extraterrestrial beings",
  "A space station orbiting a mesmerizing planet, with neon lights outlining its geometric architecture",
  "A team of robotic engineers constructing a colossal robotic being in a neon-lit assembly line, against the backdrop of a star-filled sky",
  "A futuristic robot city where humanoid robots and humans coexist, under a breathtaking canopy of swirling auroras",
  "A hidden, mystical island inhabited by ancient and beautiful creatures that possess the power to grant wishes",
  "A brave adventurer standing on the edge of a towering cliff, overlooking a breathtaking valley filled with majestic and mythical creatures",
  "A group of explorers discovering a forgotten temple on a remote, mystical island, guarded by a mythical creature of immense power",
  "A mesmerizing waterfall flowing from the top of a floating mountain on a mystical island, surrounded by radiant and ethereal creatures",
  "A young sorceress summoning a magnificent and ancient dragon to aid her in an epic battle against dark forces",
  "A legendary sword embedded in a stone, awaiting a worthy hero to release its mystical powers and embark on a grand adventure",
  "A magical forest on a mystical island, where ethereal beings dance among the luminescent trees and vibrant flora",
  "A mythical creature, part lion and part eagle, soaring through the skies of a mystical realm, with its majestic wings spread wide",
  "A group of friends encountering a wise and ancient guardian spirit during their quest for a mythical treasure on a mysterious island",
  "A mythical, underwater city populated by elegant and graceful merfolk, living in harmony with the wondrous creatures of the deep sea",
  "A futuristic cityscape blending elements of traditional Japanese architecture with neon-lit skyscrapers and bustling futuristic transportation",
  "A vibrant Korean street market at night, with colorful neon signs, traditional lanterns, and bustling crowds",
  "A futuristic Chinese city with towering holographic advertisements, high-speed maglev trains, and floating gardens",
  "A digital art installation depicting a mesmerizing blend of traditional Japanese, Korean, and Chinese cultural elements in a futuristic setting",
  "A neon-lit street in a bustling Japanese city at night, filled with glowing signs, futuristic vehicles, and bustling nightlife",
  "A futuristic marketplace in a Korean city, where holographic projections showcase a variety of goods and services",
  "A Chinese metropolis with towering skyscrapers adorned with intricate digital artworks, transforming the city into a visual marvel",
  "A nighttime view of a Japanese city, with its iconic landmarks illuminated by vibrant neon lights and reflected in a calm river",
  "A futuristic park in a Korean city, featuring interactive digital sculptures and immersive augmented reality experiences",
  "A digital art gallery in a Chinese city, showcasing a fusion of traditional and modern art forms through immersive virtual reality installations",
  "A stunning female anime character with flowing, waist-length hair, captivating eyes, and a perfectly sculpted physique, dressed in an elegant and form-fitting gown",
  "A sexy and confident female anime character with short, spiky hair, wearing a sleek, futuristic outfit that accentuates her flawless figure and fierce personality",
  "An alluring female anime character with long, voluminous curls, dressed in a revealing but tasteful warrior costume that highlights her toned muscles and athletic build",
  "A breathtaking female anime character with shimmering, ethereal hair and a slender yet curvaceous body, adorned in an intricately designed fantasy armor that showcases her grace and strength",
  "A seductive and mysterious female anime character with cascading, midnight black hair, wearing a sleek, form-fitting bodysuit that accentuates her hourglass figure and enigmatic allure",
  "An elegant and statuesque female anime character with flowing, pastel-colored hair, wearing a regal ball gown that perfectly complements her graceful posture and impeccable physique",
  "A powerful and confident female anime character with fiery red hair, clad in a skin-tight, high-tech suit that accentuates her sculpted muscles and gives her a formidable presence",
  "A captivating female anime character with vibrant, multi-colored hair and an athletic yet feminine build, dressed in a stylish and trendy outfit that showcases her unique sense of fashion",
  "A charismatic and alluring female anime character with long, flowing locks of silver hair, wearing a form-fitting, futuristic attire that highlights her perfectly proportioned body and air of mystery",
  "A captivating female anime character with wavy, emerald green hair and a lithe, dancer's physique, adorned in an intricately detailed costume that showcases her exquisite beauty and elegance",
  "A lone astronaut exploring a mysterious and fantastical desert landscape, with towering sand dunes and a sky filled with mesmerizing stars",
  "A futuristic city nestled at the bottom of the ocean, with vibrant marine life and advanced technology coexisting in harmony",
  "A woman sitting atop a grassy hill, gazing up at a sky adorned with countless twinkling stars, lost in a world of fantasy and wonder",
  "An astronaut floating weightlessly in the vast expanse of outer space, surrounded by breathtaking nebulas and distant galaxies",
  "A clock submerged in the depths of the ocean, its gears and mechanisms intertwined with vibrant coral reefs and curious sea creatures",
  "A futuristic and utopian cityscape set amidst endless fields of lush green grass, where nature and advanced technology seamlessly blend",
  "A woman adorned in celestial attire, with stars and galaxies swirling around her, symbolizing her connection to the cosmos and her role as a guardian of the universe",
  "An underwater metropolis with towering structures and illuminated walkways, where futuristic technology and marine life intertwine in a breathtaking display",
  "A vast desert landscape illuminated by a stunning sunset, with a lone woman standing amidst the golden sand, a symbol of resilience and strength",
  "An astronaut floating above a majestic grassland, with a sky full of shooting stars, representing the merging of dreams, exploration, and the beauty of the natural world",
  "A fluffy, adorable bunny playing in a snowy wonderland, surrounded by snow-covered trees and a peaceful winter landscape",
  "A cute and curious puppy exploring a vibrant grassland, with colorful flowers and tall grass swaying in the gentle breeze",
  "An endearing baby deer nestled among a serene winter scene, with snow-covered trees and a frozen pond reflecting the beauty of the surroundings",
  "A charming kitten sitting on a tree branch in a lush green park, surrounded by blooming flowers and chirping birds",
  "A delightful family of ducks waddling through a snowy park, leaving tiny footprints in the fresh white snow",
  "A group of adorable penguins huddling together in the icy landscape, with snow-covered mountains in the background",
  "A playful squirrel gathering acorns in a picturesque grassland, with golden sunlight filtering through the branches of nearby trees",
  "A cute and fuzzy baby polar bear exploring its wintry habitat, with icicles hanging from the trees and a snowy landscape stretching out as far as the eye can see",
  "A lovable panda munching on bamboo shoots in a peaceful park, surrounded by lush greenery and colorful blossoms",
  "A whimsical scene featuring a charming fox frolicking in a snow-covered field, with snowflakes falling gently from the sky and a backdrop of towering pine trees",
];
